//go:build integration

package restaurants_test

import (
	"context"
	"testing"
	"time"

	"github.com/stretchr/testify/assert"
	"go.mongodb.org/mongo-driver/bson"
	"go.mongodb.org/mongo-driver/mongo"
	"go.mongodb.org/mongo-driver/mongo/options"

	"github.com/alexgrauroca/practice-food-delivery-platform/pkg/clock"
	"github.com/alexgrauroca/practice-food-delivery-platform/pkg/infraestructure/mongodb"
	"github.com/alexgrauroca/practice-food-delivery-platform/pkg/log"
	"github.com/alexgrauroca/practice-food-delivery-platform/services/restaurant-service/internal/restaurants"
)

const dbPrefix = "restaurants_test"

type repoTestCase[P, W any] struct {
	name            string
	insertDocuments func(t *testing.T, coll *mongo.Collection)
	params          P
	want            W
	wantErr         error
}

func TestRepository_CreateRestaurant(t *testing.T) {
	now := time.Date(2025, 1, 1, 0, 0, 0, 0, time.UTC)
	logger, _ := log.NewTest()

	tests := []repoTestCase[restaurants.CreateRestaurantParams, restaurants.Restaurant]{
		{
			name: "when there is an active restaurant with the same vat code, " +
				"then it returns a restaurant already exists error",
			insertDocuments: func(t *testing.T, coll *mongo.Collection) {
				mongodb.InsertTestDocument(t, coll, restaurants.Restaurant{
					VatCode: "duplicated-vat-code",
					Active:  true,
				})
			},
			params:  restaurants.CreateRestaurantParams{VatCode: "duplicated-vat-code"},
			want:    restaurants.Restaurant{},
			wantErr: restaurants.ErrRestaurantAlreadyExists,
		},
		{
			name: "when the restaurant is created successfully, then it should return the created restaurant",
			insertDocuments: func(t *testing.T, coll *mongo.Collection) {
				mongodb.InsertTestDocument(t, coll, restaurants.Restaurant{VatCode: "another-vat-code"})
				mongodb.InsertTestDocument(t, coll, restaurants.Restaurant{
					VatCode: "valid-vat-code",
					Active:  false,
				})
			},
			params: restaurants.CreateRestaurantParams{
				VatCode:    "valid-vat-code",
				Name:       "valid-restaurant-name",
				LegalName:  "valid-legal-name",
				TaxID:      "valid-tax-id",
				TimezoneID: "Europe/London",
				Contact: restaurants.CreateContactParams{
					PhonePrefix: "+44",
					PhoneNumber: "1234567890",
					Email:       "valid-email@example.com",
					Address:     "123 Main St",
					City:        "London",
					PostalCode:  "SW1A 1AA",
					CountryCode: "GB",
				},
			},
			want: restaurants.Restaurant{
				VatCode:    "valid-vat-code",
				Name:       "valid-restaurant-name",
				LegalName:  "valid-legal-name",
				TaxID:      "valid-tax-id",
				TimezoneID: "Europe/London",
				Contact: restaurants.Contact{
					PhonePrefix: "+44",
					PhoneNumber: "1234567890",
					Email:       "valid-email@example.com",
					Address:     "123 Main St",
					City:        "London",
					PostalCode:  "SW1A 1AA",
					CountryCode: "GB",
				},
				Active:    true,
				CreatedAt: now,
				UpdatedAt: now,
			},
			wantErr: nil,
		},
	}

	for _, tt := range tests {
		t.Run(tt.name, func(t *testing.T) {
			tdb := mongodb.NewTestDB(t, dbPrefix)
			defer tdb.Close(t)

			coll := setupTestRestaurantsCollection(t, tdb.DB)
			if tt.insertDocuments != nil {
				tt.insertDocuments(t, coll)
			}

			repo := restaurants.NewRepository(logger, tdb.DB, clock.FixedClock{FixedTime: now})
			got, err := repo.CreateRestaurant(context.Background(), tt.params)

			// Error assertion
			assert.ErrorIs(t, err, tt.wantErr)

			// Validating the got only if there is no error expected
			if tt.wantErr == nil {
				// As the RestaurantID is generated by MongoDB, we just check that it is not empty
				assert.NotEmpty(t, got.ID, "RestaurantID should not be empty")

				// Doing this as in that way, I can do a direct equal assertion between the want and got
				tt.want.ID = got.ID
				assert.Equal(t, tt.want, got)
			}
		})
	}
}

func setupTestRestaurantsCollection(t *testing.T, db *mongo.Database) *mongo.Collection {
	ctx, cancel := context.WithTimeout(context.Background(), 5*time.Second)
	defer cancel()

	coll := db.Collection(restaurants.CollectionName)

	// Create unique index on email
	indexModel := mongo.IndexModel{
		Keys: bson.D{{Key: restaurants.FieldVatCode, Value: 1}},
		Options: options.Index().
			SetUnique(true).
			SetPartialFilterExpression(bson.D{{Key: restaurants.FieldActive, Value: true}}),
	}
	if _, err := coll.Indexes().CreateOne(ctx, indexModel); err != nil {
		t.Fatalf("Failed to create unique index: %v", err)
	}

	return coll
}
