/*
Authentication Service API

API documentation for the authentication service.  This service provides endpoints for customer and staff registration and authentication. 

API version: 1.0.0
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package authclient

import (
	"encoding/json"
	"bytes"
	"fmt"
)

// checks if the LoginStaffRequest type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &LoginStaffRequest{}

// LoginStaffRequest struct for LoginStaffRequest
type LoginStaffRequest struct {
	Email string `json:"email"`
	RestaurantId string `json:"restaurant_id" validate:"regexp=^[0-9a-fA-F]{24}$"`
	Password string `json:"password"`
}

type _LoginStaffRequest LoginStaffRequest

// NewLoginStaffRequest instantiates a new LoginStaffRequest object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewLoginStaffRequest(email string, restaurantId string, password string) *LoginStaffRequest {
	this := LoginStaffRequest{}
	this.Email = email
	this.RestaurantId = restaurantId
	this.Password = password
	return &this
}

// NewLoginStaffRequestWithDefaults instantiates a new LoginStaffRequest object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewLoginStaffRequestWithDefaults() *LoginStaffRequest {
	this := LoginStaffRequest{}
	return &this
}

// GetEmail returns the Email field value
func (o *LoginStaffRequest) GetEmail() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.Email
}

// GetEmailOk returns a tuple with the Email field value
// and a boolean to check if the value has been set.
func (o *LoginStaffRequest) GetEmailOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Email, true
}

// SetEmail sets field value
func (o *LoginStaffRequest) SetEmail(v string) {
	o.Email = v
}

// GetRestaurantId returns the RestaurantId field value
func (o *LoginStaffRequest) GetRestaurantId() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.RestaurantId
}

// GetRestaurantIdOk returns a tuple with the RestaurantId field value
// and a boolean to check if the value has been set.
func (o *LoginStaffRequest) GetRestaurantIdOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.RestaurantId, true
}

// SetRestaurantId sets field value
func (o *LoginStaffRequest) SetRestaurantId(v string) {
	o.RestaurantId = v
}

// GetPassword returns the Password field value
func (o *LoginStaffRequest) GetPassword() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.Password
}

// GetPasswordOk returns a tuple with the Password field value
// and a boolean to check if the value has been set.
func (o *LoginStaffRequest) GetPasswordOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Password, true
}

// SetPassword sets field value
func (o *LoginStaffRequest) SetPassword(v string) {
	o.Password = v
}

func (o LoginStaffRequest) MarshalJSON() ([]byte, error) {
	toSerialize,err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o LoginStaffRequest) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	toSerialize["email"] = o.Email
	toSerialize["restaurant_id"] = o.RestaurantId
	toSerialize["password"] = o.Password
	return toSerialize, nil
}

func (o *LoginStaffRequest) UnmarshalJSON(data []byte) (err error) {
	// This validates that all required properties are included in the JSON object
	// by unmarshalling the object into a generic map with string keys and checking
	// that every required field exists as a key in the generic map.
	requiredProperties := []string{
		"email",
		"restaurant_id",
		"password",
	}

	allProperties := make(map[string]interface{})

	err = json.Unmarshal(data, &allProperties)

	if err != nil {
		return err;
	}

	for _, requiredProperty := range(requiredProperties) {
		if _, exists := allProperties[requiredProperty]; !exists {
			return fmt.Errorf("no value given for required property %v", requiredProperty)
		}
	}

	varLoginStaffRequest := _LoginStaffRequest{}

	decoder := json.NewDecoder(bytes.NewReader(data))
	decoder.DisallowUnknownFields()
	err = decoder.Decode(&varLoginStaffRequest)

	if err != nil {
		return err
	}

	*o = LoginStaffRequest(varLoginStaffRequest)

	return err
}

type NullableLoginStaffRequest struct {
	value *LoginStaffRequest
	isSet bool
}

func (v NullableLoginStaffRequest) Get() *LoginStaffRequest {
	return v.value
}

func (v *NullableLoginStaffRequest) Set(val *LoginStaffRequest) {
	v.value = val
	v.isSet = true
}

func (v NullableLoginStaffRequest) IsSet() bool {
	return v.isSet
}

func (v *NullableLoginStaffRequest) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableLoginStaffRequest(val *LoginStaffRequest) *NullableLoginStaffRequest {
	return &NullableLoginStaffRequest{value: val, isSet: true}
}

func (v NullableLoginStaffRequest) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableLoginStaffRequest) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


