/*
Authentication Service API

API documentation for the authentication service.  This service provides endpoints for customer and staff registration and authentication. 

API version: 1.0.0
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package authclient

import (
	"encoding/json"
	"bytes"
	"fmt"
)

// checks if the LoginCustomerRequest type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &LoginCustomerRequest{}

// LoginCustomerRequest struct for LoginCustomerRequest
type LoginCustomerRequest struct {
	// Customer's email address
	Email string `json:"email"`
	// Customer's password
	Password string `json:"password"`
}

type _LoginCustomerRequest LoginCustomerRequest

// NewLoginCustomerRequest instantiates a new LoginCustomerRequest object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewLoginCustomerRequest(email string, password string) *LoginCustomerRequest {
	this := LoginCustomerRequest{}
	this.Email = email
	this.Password = password
	return &this
}

// NewLoginCustomerRequestWithDefaults instantiates a new LoginCustomerRequest object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewLoginCustomerRequestWithDefaults() *LoginCustomerRequest {
	this := LoginCustomerRequest{}
	return &this
}

// GetEmail returns the Email field value
func (o *LoginCustomerRequest) GetEmail() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.Email
}

// GetEmailOk returns a tuple with the Email field value
// and a boolean to check if the value has been set.
func (o *LoginCustomerRequest) GetEmailOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Email, true
}

// SetEmail sets field value
func (o *LoginCustomerRequest) SetEmail(v string) {
	o.Email = v
}

// GetPassword returns the Password field value
func (o *LoginCustomerRequest) GetPassword() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.Password
}

// GetPasswordOk returns a tuple with the Password field value
// and a boolean to check if the value has been set.
func (o *LoginCustomerRequest) GetPasswordOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Password, true
}

// SetPassword sets field value
func (o *LoginCustomerRequest) SetPassword(v string) {
	o.Password = v
}

func (o LoginCustomerRequest) MarshalJSON() ([]byte, error) {
	toSerialize,err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o LoginCustomerRequest) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	toSerialize["email"] = o.Email
	toSerialize["password"] = o.Password
	return toSerialize, nil
}

func (o *LoginCustomerRequest) UnmarshalJSON(data []byte) (err error) {
	// This validates that all required properties are included in the JSON object
	// by unmarshalling the object into a generic map with string keys and checking
	// that every required field exists as a key in the generic map.
	requiredProperties := []string{
		"email",
		"password",
	}

	allProperties := make(map[string]interface{})

	err = json.Unmarshal(data, &allProperties)

	if err != nil {
		return err;
	}

	for _, requiredProperty := range(requiredProperties) {
		if _, exists := allProperties[requiredProperty]; !exists {
			return fmt.Errorf("no value given for required property %v", requiredProperty)
		}
	}

	varLoginCustomerRequest := _LoginCustomerRequest{}

	decoder := json.NewDecoder(bytes.NewReader(data))
	decoder.DisallowUnknownFields()
	err = decoder.Decode(&varLoginCustomerRequest)

	if err != nil {
		return err
	}

	*o = LoginCustomerRequest(varLoginCustomerRequest)

	return err
}

type NullableLoginCustomerRequest struct {
	value *LoginCustomerRequest
	isSet bool
}

func (v NullableLoginCustomerRequest) Get() *LoginCustomerRequest {
	return v.value
}

func (v *NullableLoginCustomerRequest) Set(val *LoginCustomerRequest) {
	v.value = val
	v.isSet = true
}

func (v NullableLoginCustomerRequest) IsSet() bool {
	return v.isSet
}

func (v *NullableLoginCustomerRequest) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableLoginCustomerRequest(val *LoginCustomerRequest) *NullableLoginCustomerRequest {
	return &NullableLoginCustomerRequest{value: val, isSet: true}
}

func (v NullableLoginCustomerRequest) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableLoginCustomerRequest) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


