/*
Authentication Service API

API documentation for the authentication service.  This service provides endpoints for customer and staff registration and authentication. 

API version: 1.0.0
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package authclient

import (
	"encoding/json"
	"bytes"
	"fmt"
)

// checks if the RefreshCustomerRequest type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &RefreshCustomerRequest{}

// RefreshCustomerRequest struct for RefreshCustomerRequest
type RefreshCustomerRequest struct {
	// The expired JWT access token
	AccessToken string `json:"access_token"`
	// The refresh token to use
	RefreshToken string `json:"refresh_token"`
}

type _RefreshCustomerRequest RefreshCustomerRequest

// NewRefreshCustomerRequest instantiates a new RefreshCustomerRequest object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewRefreshCustomerRequest(accessToken string, refreshToken string) *RefreshCustomerRequest {
	this := RefreshCustomerRequest{}
	this.AccessToken = accessToken
	this.RefreshToken = refreshToken
	return &this
}

// NewRefreshCustomerRequestWithDefaults instantiates a new RefreshCustomerRequest object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewRefreshCustomerRequestWithDefaults() *RefreshCustomerRequest {
	this := RefreshCustomerRequest{}
	return &this
}

// GetAccessToken returns the AccessToken field value
func (o *RefreshCustomerRequest) GetAccessToken() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.AccessToken
}

// GetAccessTokenOk returns a tuple with the AccessToken field value
// and a boolean to check if the value has been set.
func (o *RefreshCustomerRequest) GetAccessTokenOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.AccessToken, true
}

// SetAccessToken sets field value
func (o *RefreshCustomerRequest) SetAccessToken(v string) {
	o.AccessToken = v
}

// GetRefreshToken returns the RefreshToken field value
func (o *RefreshCustomerRequest) GetRefreshToken() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.RefreshToken
}

// GetRefreshTokenOk returns a tuple with the RefreshToken field value
// and a boolean to check if the value has been set.
func (o *RefreshCustomerRequest) GetRefreshTokenOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.RefreshToken, true
}

// SetRefreshToken sets field value
func (o *RefreshCustomerRequest) SetRefreshToken(v string) {
	o.RefreshToken = v
}

func (o RefreshCustomerRequest) MarshalJSON() ([]byte, error) {
	toSerialize,err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o RefreshCustomerRequest) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	toSerialize["access_token"] = o.AccessToken
	toSerialize["refresh_token"] = o.RefreshToken
	return toSerialize, nil
}

func (o *RefreshCustomerRequest) UnmarshalJSON(data []byte) (err error) {
	// This validates that all required properties are included in the JSON object
	// by unmarshalling the object into a generic map with string keys and checking
	// that every required field exists as a key in the generic map.
	requiredProperties := []string{
		"access_token",
		"refresh_token",
	}

	allProperties := make(map[string]interface{})

	err = json.Unmarshal(data, &allProperties)

	if err != nil {
		return err;
	}

	for _, requiredProperty := range(requiredProperties) {
		if _, exists := allProperties[requiredProperty]; !exists {
			return fmt.Errorf("no value given for required property %v", requiredProperty)
		}
	}

	varRefreshCustomerRequest := _RefreshCustomerRequest{}

	decoder := json.NewDecoder(bytes.NewReader(data))
	decoder.DisallowUnknownFields()
	err = decoder.Decode(&varRefreshCustomerRequest)

	if err != nil {
		return err
	}

	*o = RefreshCustomerRequest(varRefreshCustomerRequest)

	return err
}

type NullableRefreshCustomerRequest struct {
	value *RefreshCustomerRequest
	isSet bool
}

func (v NullableRefreshCustomerRequest) Get() *RefreshCustomerRequest {
	return v.value
}

func (v *NullableRefreshCustomerRequest) Set(val *RefreshCustomerRequest) {
	v.value = val
	v.isSet = true
}

func (v NullableRefreshCustomerRequest) IsSet() bool {
	return v.isSet
}

func (v *NullableRefreshCustomerRequest) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableRefreshCustomerRequest(val *RefreshCustomerRequest) *NullableRefreshCustomerRequest {
	return &NullableRefreshCustomerRequest{value: val, isSet: true}
}

func (v NullableRefreshCustomerRequest) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableRefreshCustomerRequest) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


