/*
Authentication Service API

API documentation for the authentication service.  This service provides endpoints for customer and staff registration and authentication. 

API version: 1.0.0
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package authclient

import (
	"encoding/json"
	"bytes"
	"fmt"
)

// checks if the RefreshResponse type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &RefreshResponse{}

// RefreshResponse struct for RefreshResponse
type RefreshResponse struct {
	// JWT access token for API authentication
	AccessToken string `json:"access_token"`
	// Token used to obtain a new access token when it expires
	RefreshToken string `json:"refresh_token"`
	// Access token expiration time in seconds
	ExpiresIn int32 `json:"expires_in"`
	// Access token type
	TokenType string `json:"token_type"`
}

type _RefreshResponse RefreshResponse

// NewRefreshResponse instantiates a new RefreshResponse object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewRefreshResponse(accessToken string, refreshToken string, expiresIn int32, tokenType string) *RefreshResponse {
	this := RefreshResponse{}
	this.AccessToken = accessToken
	this.RefreshToken = refreshToken
	this.ExpiresIn = expiresIn
	this.TokenType = tokenType
	return &this
}

// NewRefreshResponseWithDefaults instantiates a new RefreshResponse object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewRefreshResponseWithDefaults() *RefreshResponse {
	this := RefreshResponse{}
	return &this
}

// GetAccessToken returns the AccessToken field value
func (o *RefreshResponse) GetAccessToken() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.AccessToken
}

// GetAccessTokenOk returns a tuple with the AccessToken field value
// and a boolean to check if the value has been set.
func (o *RefreshResponse) GetAccessTokenOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.AccessToken, true
}

// SetAccessToken sets field value
func (o *RefreshResponse) SetAccessToken(v string) {
	o.AccessToken = v
}

// GetRefreshToken returns the RefreshToken field value
func (o *RefreshResponse) GetRefreshToken() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.RefreshToken
}

// GetRefreshTokenOk returns a tuple with the RefreshToken field value
// and a boolean to check if the value has been set.
func (o *RefreshResponse) GetRefreshTokenOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.RefreshToken, true
}

// SetRefreshToken sets field value
func (o *RefreshResponse) SetRefreshToken(v string) {
	o.RefreshToken = v
}

// GetExpiresIn returns the ExpiresIn field value
func (o *RefreshResponse) GetExpiresIn() int32 {
	if o == nil {
		var ret int32
		return ret
	}

	return o.ExpiresIn
}

// GetExpiresInOk returns a tuple with the ExpiresIn field value
// and a boolean to check if the value has been set.
func (o *RefreshResponse) GetExpiresInOk() (*int32, bool) {
	if o == nil {
		return nil, false
	}
	return &o.ExpiresIn, true
}

// SetExpiresIn sets field value
func (o *RefreshResponse) SetExpiresIn(v int32) {
	o.ExpiresIn = v
}

// GetTokenType returns the TokenType field value
func (o *RefreshResponse) GetTokenType() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.TokenType
}

// GetTokenTypeOk returns a tuple with the TokenType field value
// and a boolean to check if the value has been set.
func (o *RefreshResponse) GetTokenTypeOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.TokenType, true
}

// SetTokenType sets field value
func (o *RefreshResponse) SetTokenType(v string) {
	o.TokenType = v
}

func (o RefreshResponse) MarshalJSON() ([]byte, error) {
	toSerialize,err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o RefreshResponse) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	toSerialize["access_token"] = o.AccessToken
	toSerialize["refresh_token"] = o.RefreshToken
	toSerialize["expires_in"] = o.ExpiresIn
	toSerialize["token_type"] = o.TokenType
	return toSerialize, nil
}

func (o *RefreshResponse) UnmarshalJSON(data []byte) (err error) {
	// This validates that all required properties are included in the JSON object
	// by unmarshalling the object into a generic map with string keys and checking
	// that every required field exists as a key in the generic map.
	requiredProperties := []string{
		"access_token",
		"refresh_token",
		"expires_in",
		"token_type",
	}

	allProperties := make(map[string]interface{})

	err = json.Unmarshal(data, &allProperties)

	if err != nil {
		return err;
	}

	for _, requiredProperty := range(requiredProperties) {
		if _, exists := allProperties[requiredProperty]; !exists {
			return fmt.Errorf("no value given for required property %v", requiredProperty)
		}
	}

	varRefreshResponse := _RefreshResponse{}

	decoder := json.NewDecoder(bytes.NewReader(data))
	decoder.DisallowUnknownFields()
	err = decoder.Decode(&varRefreshResponse)

	if err != nil {
		return err
	}

	*o = RefreshResponse(varRefreshResponse)

	return err
}

type NullableRefreshResponse struct {
	value *RefreshResponse
	isSet bool
}

func (v NullableRefreshResponse) Get() *RefreshResponse {
	return v.value
}

func (v *NullableRefreshResponse) Set(val *RefreshResponse) {
	v.value = val
	v.isSet = true
}

func (v NullableRefreshResponse) IsSet() bool {
	return v.isSet
}

func (v *NullableRefreshResponse) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableRefreshResponse(val *RefreshResponse) *NullableRefreshResponse {
	return &NullableRefreshResponse{value: val, isSet: true}
}

func (v NullableRefreshResponse) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableRefreshResponse) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


