/*
Authentication Service API

API documentation for the authentication service.  This service provides endpoints for customer and staff registration and authentication. 

API version: 1.0.0
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package authclient

import (
	"encoding/json"
	"time"
	"bytes"
	"fmt"
)

// checks if the RegisterStaffResponse type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &RegisterStaffResponse{}

// RegisterStaffResponse struct for RegisterStaffResponse
type RegisterStaffResponse struct {
	// Unique staff identifier in the auth service
	Id string `json:"id" validate:"regexp=^[0-9a-fA-F]{24}$"`
	// Staff's email address
	Email string `json:"email"`
	// Unique restaurant identifier in the auth service
	RestaurantId *string `json:"restaurant_id,omitempty" validate:"regexp=^[0-9a-fA-F]{24}$"`
	// Staff creation timestamp
	CreatedAt time.Time `json:"created_at"`
	// Staff update timestamp
	UpdatedAt *time.Time `json:"updated_at,omitempty"`
}

type _RegisterStaffResponse RegisterStaffResponse

// NewRegisterStaffResponse instantiates a new RegisterStaffResponse object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewRegisterStaffResponse(id string, email string, createdAt time.Time) *RegisterStaffResponse {
	this := RegisterStaffResponse{}
	this.Id = id
	this.Email = email
	this.CreatedAt = createdAt
	return &this
}

// NewRegisterStaffResponseWithDefaults instantiates a new RegisterStaffResponse object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewRegisterStaffResponseWithDefaults() *RegisterStaffResponse {
	this := RegisterStaffResponse{}
	return &this
}

// GetId returns the Id field value
func (o *RegisterStaffResponse) GetId() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.Id
}

// GetIdOk returns a tuple with the Id field value
// and a boolean to check if the value has been set.
func (o *RegisterStaffResponse) GetIdOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Id, true
}

// SetId sets field value
func (o *RegisterStaffResponse) SetId(v string) {
	o.Id = v
}

// GetEmail returns the Email field value
func (o *RegisterStaffResponse) GetEmail() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.Email
}

// GetEmailOk returns a tuple with the Email field value
// and a boolean to check if the value has been set.
func (o *RegisterStaffResponse) GetEmailOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Email, true
}

// SetEmail sets field value
func (o *RegisterStaffResponse) SetEmail(v string) {
	o.Email = v
}

// GetRestaurantId returns the RestaurantId field value if set, zero value otherwise.
func (o *RegisterStaffResponse) GetRestaurantId() string {
	if o == nil || IsNil(o.RestaurantId) {
		var ret string
		return ret
	}
	return *o.RestaurantId
}

// GetRestaurantIdOk returns a tuple with the RestaurantId field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *RegisterStaffResponse) GetRestaurantIdOk() (*string, bool) {
	if o == nil || IsNil(o.RestaurantId) {
		return nil, false
	}
	return o.RestaurantId, true
}

// HasRestaurantId returns a boolean if a field has been set.
func (o *RegisterStaffResponse) HasRestaurantId() bool {
	if o != nil && !IsNil(o.RestaurantId) {
		return true
	}

	return false
}

// SetRestaurantId gets a reference to the given string and assigns it to the RestaurantId field.
func (o *RegisterStaffResponse) SetRestaurantId(v string) {
	o.RestaurantId = &v
}

// GetCreatedAt returns the CreatedAt field value
func (o *RegisterStaffResponse) GetCreatedAt() time.Time {
	if o == nil {
		var ret time.Time
		return ret
	}

	return o.CreatedAt
}

// GetCreatedAtOk returns a tuple with the CreatedAt field value
// and a boolean to check if the value has been set.
func (o *RegisterStaffResponse) GetCreatedAtOk() (*time.Time, bool) {
	if o == nil {
		return nil, false
	}
	return &o.CreatedAt, true
}

// SetCreatedAt sets field value
func (o *RegisterStaffResponse) SetCreatedAt(v time.Time) {
	o.CreatedAt = v
}

// GetUpdatedAt returns the UpdatedAt field value if set, zero value otherwise.
func (o *RegisterStaffResponse) GetUpdatedAt() time.Time {
	if o == nil || IsNil(o.UpdatedAt) {
		var ret time.Time
		return ret
	}
	return *o.UpdatedAt
}

// GetUpdatedAtOk returns a tuple with the UpdatedAt field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *RegisterStaffResponse) GetUpdatedAtOk() (*time.Time, bool) {
	if o == nil || IsNil(o.UpdatedAt) {
		return nil, false
	}
	return o.UpdatedAt, true
}

// HasUpdatedAt returns a boolean if a field has been set.
func (o *RegisterStaffResponse) HasUpdatedAt() bool {
	if o != nil && !IsNil(o.UpdatedAt) {
		return true
	}

	return false
}

// SetUpdatedAt gets a reference to the given time.Time and assigns it to the UpdatedAt field.
func (o *RegisterStaffResponse) SetUpdatedAt(v time.Time) {
	o.UpdatedAt = &v
}

func (o RegisterStaffResponse) MarshalJSON() ([]byte, error) {
	toSerialize,err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o RegisterStaffResponse) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	toSerialize["id"] = o.Id
	toSerialize["email"] = o.Email
	if !IsNil(o.RestaurantId) {
		toSerialize["restaurant_id"] = o.RestaurantId
	}
	toSerialize["created_at"] = o.CreatedAt
	if !IsNil(o.UpdatedAt) {
		toSerialize["updated_at"] = o.UpdatedAt
	}
	return toSerialize, nil
}

func (o *RegisterStaffResponse) UnmarshalJSON(data []byte) (err error) {
	// This validates that all required properties are included in the JSON object
	// by unmarshalling the object into a generic map with string keys and checking
	// that every required field exists as a key in the generic map.
	requiredProperties := []string{
		"id",
		"email",
		"created_at",
	}

	allProperties := make(map[string]interface{})

	err = json.Unmarshal(data, &allProperties)

	if err != nil {
		return err;
	}

	for _, requiredProperty := range(requiredProperties) {
		if _, exists := allProperties[requiredProperty]; !exists {
			return fmt.Errorf("no value given for required property %v", requiredProperty)
		}
	}

	varRegisterStaffResponse := _RegisterStaffResponse{}

	decoder := json.NewDecoder(bytes.NewReader(data))
	decoder.DisallowUnknownFields()
	err = decoder.Decode(&varRegisterStaffResponse)

	if err != nil {
		return err
	}

	*o = RegisterStaffResponse(varRegisterStaffResponse)

	return err
}

type NullableRegisterStaffResponse struct {
	value *RegisterStaffResponse
	isSet bool
}

func (v NullableRegisterStaffResponse) Get() *RegisterStaffResponse {
	return v.value
}

func (v *NullableRegisterStaffResponse) Set(val *RegisterStaffResponse) {
	v.value = val
	v.isSet = true
}

func (v NullableRegisterStaffResponse) IsSet() bool {
	return v.isSet
}

func (v *NullableRegisterStaffResponse) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableRegisterStaffResponse(val *RegisterStaffResponse) *NullableRegisterStaffResponse {
	return &NullableRegisterStaffResponse{value: val, isSet: true}
}

func (v NullableRegisterStaffResponse) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableRegisterStaffResponse) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


