/*
Restaurant Service API

API documentation for the restaurant service.  This service provides endpoints for restaurant and staff registration and management. 

API version: 1.0.0
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package restaurantclient

import (
	"encoding/json"
	"time"
	"bytes"
	"fmt"
)

// checks if the Staff type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &Staff{}

// Staff struct for Staff
type Staff struct {
	// Unique staff identifier
	Id string `json:"id" validate:"regexp=^[0-9a-fA-F]{24}$"`
	// The email address of the staff
	Email string `json:"email"`
	// Unique restaurant identifier
	RestaurantId string `json:"restaurant_id" validate:"regexp=^[0-9a-fA-F]{24}$"`
	// Whether the staff is the restaurant owner
	Owner bool `json:"owner"`
	// The full name of the staff
	Name string `json:"name"`
	// Staff's address
	Address string `json:"address"`
	// Staff's city
	City string `json:"city"`
	// Staff's postal code
	PostalCode string `json:"postal_code"`
	// Staff's country code in ISO 3166-1 alpha-2 format
	CountryCode string `json:"country_code"`
	// The timestamp when the staff was created
	CreatedAt time.Time `json:"created_at"`
	// The timestamp when the staff was last updated
	UpdatedAt time.Time `json:"updated_at"`
}

type _Staff Staff

// NewStaff instantiates a new Staff object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewStaff(id string, email string, restaurantId string, owner bool, name string, address string, city string, postalCode string, countryCode string, createdAt time.Time, updatedAt time.Time) *Staff {
	this := Staff{}
	this.Id = id
	this.Email = email
	this.RestaurantId = restaurantId
	this.Owner = owner
	this.Name = name
	this.Address = address
	this.City = city
	this.PostalCode = postalCode
	this.CountryCode = countryCode
	this.CreatedAt = createdAt
	this.UpdatedAt = updatedAt
	return &this
}

// NewStaffWithDefaults instantiates a new Staff object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewStaffWithDefaults() *Staff {
	this := Staff{}
	return &this
}

// GetId returns the Id field value
func (o *Staff) GetId() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.Id
}

// GetIdOk returns a tuple with the Id field value
// and a boolean to check if the value has been set.
func (o *Staff) GetIdOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Id, true
}

// SetId sets field value
func (o *Staff) SetId(v string) {
	o.Id = v
}

// GetEmail returns the Email field value
func (o *Staff) GetEmail() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.Email
}

// GetEmailOk returns a tuple with the Email field value
// and a boolean to check if the value has been set.
func (o *Staff) GetEmailOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Email, true
}

// SetEmail sets field value
func (o *Staff) SetEmail(v string) {
	o.Email = v
}

// GetRestaurantId returns the RestaurantId field value
func (o *Staff) GetRestaurantId() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.RestaurantId
}

// GetRestaurantIdOk returns a tuple with the RestaurantId field value
// and a boolean to check if the value has been set.
func (o *Staff) GetRestaurantIdOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.RestaurantId, true
}

// SetRestaurantId sets field value
func (o *Staff) SetRestaurantId(v string) {
	o.RestaurantId = v
}

// GetOwner returns the Owner field value
func (o *Staff) GetOwner() bool {
	if o == nil {
		var ret bool
		return ret
	}

	return o.Owner
}

// GetOwnerOk returns a tuple with the Owner field value
// and a boolean to check if the value has been set.
func (o *Staff) GetOwnerOk() (*bool, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Owner, true
}

// SetOwner sets field value
func (o *Staff) SetOwner(v bool) {
	o.Owner = v
}

// GetName returns the Name field value
func (o *Staff) GetName() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.Name
}

// GetNameOk returns a tuple with the Name field value
// and a boolean to check if the value has been set.
func (o *Staff) GetNameOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Name, true
}

// SetName sets field value
func (o *Staff) SetName(v string) {
	o.Name = v
}

// GetAddress returns the Address field value
func (o *Staff) GetAddress() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.Address
}

// GetAddressOk returns a tuple with the Address field value
// and a boolean to check if the value has been set.
func (o *Staff) GetAddressOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Address, true
}

// SetAddress sets field value
func (o *Staff) SetAddress(v string) {
	o.Address = v
}

// GetCity returns the City field value
func (o *Staff) GetCity() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.City
}

// GetCityOk returns a tuple with the City field value
// and a boolean to check if the value has been set.
func (o *Staff) GetCityOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.City, true
}

// SetCity sets field value
func (o *Staff) SetCity(v string) {
	o.City = v
}

// GetPostalCode returns the PostalCode field value
func (o *Staff) GetPostalCode() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.PostalCode
}

// GetPostalCodeOk returns a tuple with the PostalCode field value
// and a boolean to check if the value has been set.
func (o *Staff) GetPostalCodeOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.PostalCode, true
}

// SetPostalCode sets field value
func (o *Staff) SetPostalCode(v string) {
	o.PostalCode = v
}

// GetCountryCode returns the CountryCode field value
func (o *Staff) GetCountryCode() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.CountryCode
}

// GetCountryCodeOk returns a tuple with the CountryCode field value
// and a boolean to check if the value has been set.
func (o *Staff) GetCountryCodeOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.CountryCode, true
}

// SetCountryCode sets field value
func (o *Staff) SetCountryCode(v string) {
	o.CountryCode = v
}

// GetCreatedAt returns the CreatedAt field value
func (o *Staff) GetCreatedAt() time.Time {
	if o == nil {
		var ret time.Time
		return ret
	}

	return o.CreatedAt
}

// GetCreatedAtOk returns a tuple with the CreatedAt field value
// and a boolean to check if the value has been set.
func (o *Staff) GetCreatedAtOk() (*time.Time, bool) {
	if o == nil {
		return nil, false
	}
	return &o.CreatedAt, true
}

// SetCreatedAt sets field value
func (o *Staff) SetCreatedAt(v time.Time) {
	o.CreatedAt = v
}

// GetUpdatedAt returns the UpdatedAt field value
func (o *Staff) GetUpdatedAt() time.Time {
	if o == nil {
		var ret time.Time
		return ret
	}

	return o.UpdatedAt
}

// GetUpdatedAtOk returns a tuple with the UpdatedAt field value
// and a boolean to check if the value has been set.
func (o *Staff) GetUpdatedAtOk() (*time.Time, bool) {
	if o == nil {
		return nil, false
	}
	return &o.UpdatedAt, true
}

// SetUpdatedAt sets field value
func (o *Staff) SetUpdatedAt(v time.Time) {
	o.UpdatedAt = v
}

func (o Staff) MarshalJSON() ([]byte, error) {
	toSerialize,err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o Staff) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	toSerialize["id"] = o.Id
	toSerialize["email"] = o.Email
	toSerialize["restaurant_id"] = o.RestaurantId
	toSerialize["owner"] = o.Owner
	toSerialize["name"] = o.Name
	toSerialize["address"] = o.Address
	toSerialize["city"] = o.City
	toSerialize["postal_code"] = o.PostalCode
	toSerialize["country_code"] = o.CountryCode
	toSerialize["created_at"] = o.CreatedAt
	toSerialize["updated_at"] = o.UpdatedAt
	return toSerialize, nil
}

func (o *Staff) UnmarshalJSON(data []byte) (err error) {
	// This validates that all required properties are included in the JSON object
	// by unmarshalling the object into a generic map with string keys and checking
	// that every required field exists as a key in the generic map.
	requiredProperties := []string{
		"id",
		"email",
		"restaurant_id",
		"owner",
		"name",
		"address",
		"city",
		"postal_code",
		"country_code",
		"created_at",
		"updated_at",
	}

	allProperties := make(map[string]interface{})

	err = json.Unmarshal(data, &allProperties)

	if err != nil {
		return err;
	}

	for _, requiredProperty := range(requiredProperties) {
		if _, exists := allProperties[requiredProperty]; !exists {
			return fmt.Errorf("no value given for required property %v", requiredProperty)
		}
	}

	varStaff := _Staff{}

	decoder := json.NewDecoder(bytes.NewReader(data))
	decoder.DisallowUnknownFields()
	err = decoder.Decode(&varStaff)

	if err != nil {
		return err
	}

	*o = Staff(varStaff)

	return err
}

type NullableStaff struct {
	value *Staff
	isSet bool
}

func (v NullableStaff) Get() *Staff {
	return v.value
}

func (v *NullableStaff) Set(val *Staff) {
	v.value = val
	v.isSet = true
}

func (v NullableStaff) IsSet() bool {
	return v.isSet
}

func (v *NullableStaff) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableStaff(val *Staff) *NullableStaff {
	return &NullableStaff{value: val, isSet: true}
}

func (v NullableStaff) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableStaff) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


