/*
Restaurant Service API

API documentation for the restaurant service.  This service provides endpoints for restaurant and staff registration and management. 

API version: 1.0.0
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package restaurantclient

import (
	"encoding/json"
	"bytes"
	"fmt"
)

// checks if the RestaurantContact type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &RestaurantContact{}

// RestaurantContact struct for RestaurantContact
type RestaurantContact struct {
	// E.164 country/area prefix, leading '+' required
	PhonePrefix string `json:"phone_prefix" validate:"regexp=^\\\\+\\\\d{1,4}$"`
	// Restaurant's phone number
	PhoneNumber string `json:"phone_number" validate:"regexp=^\\\\d{4,14}$"`
	// Restaurant's email address
	Email string `json:"email" validate:"regexp=^[\\\\w\\\\.-]+@[\\\\w\\\\.-]+\\\\.\\\\w{2,}$"`
	// Restaurant's address
	Address string `json:"address"`
	// Restaurant's city
	City string `json:"city"`
	// Restaurant's postal code
	PostalCode string `json:"postal_code"`
	// Restaurant's country code in ISO 3166-1 alpha-2 format
	CountryCode string `json:"country_code"`
}

type _RestaurantContact RestaurantContact

// NewRestaurantContact instantiates a new RestaurantContact object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewRestaurantContact(phonePrefix string, phoneNumber string, email string, address string, city string, postalCode string, countryCode string) *RestaurantContact {
	this := RestaurantContact{}
	this.PhonePrefix = phonePrefix
	this.PhoneNumber = phoneNumber
	this.Email = email
	this.Address = address
	this.City = city
	this.PostalCode = postalCode
	this.CountryCode = countryCode
	return &this
}

// NewRestaurantContactWithDefaults instantiates a new RestaurantContact object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewRestaurantContactWithDefaults() *RestaurantContact {
	this := RestaurantContact{}
	return &this
}

// GetPhonePrefix returns the PhonePrefix field value
func (o *RestaurantContact) GetPhonePrefix() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.PhonePrefix
}

// GetPhonePrefixOk returns a tuple with the PhonePrefix field value
// and a boolean to check if the value has been set.
func (o *RestaurantContact) GetPhonePrefixOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.PhonePrefix, true
}

// SetPhonePrefix sets field value
func (o *RestaurantContact) SetPhonePrefix(v string) {
	o.PhonePrefix = v
}

// GetPhoneNumber returns the PhoneNumber field value
func (o *RestaurantContact) GetPhoneNumber() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.PhoneNumber
}

// GetPhoneNumberOk returns a tuple with the PhoneNumber field value
// and a boolean to check if the value has been set.
func (o *RestaurantContact) GetPhoneNumberOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.PhoneNumber, true
}

// SetPhoneNumber sets field value
func (o *RestaurantContact) SetPhoneNumber(v string) {
	o.PhoneNumber = v
}

// GetEmail returns the Email field value
func (o *RestaurantContact) GetEmail() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.Email
}

// GetEmailOk returns a tuple with the Email field value
// and a boolean to check if the value has been set.
func (o *RestaurantContact) GetEmailOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Email, true
}

// SetEmail sets field value
func (o *RestaurantContact) SetEmail(v string) {
	o.Email = v
}

// GetAddress returns the Address field value
func (o *RestaurantContact) GetAddress() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.Address
}

// GetAddressOk returns a tuple with the Address field value
// and a boolean to check if the value has been set.
func (o *RestaurantContact) GetAddressOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Address, true
}

// SetAddress sets field value
func (o *RestaurantContact) SetAddress(v string) {
	o.Address = v
}

// GetCity returns the City field value
func (o *RestaurantContact) GetCity() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.City
}

// GetCityOk returns a tuple with the City field value
// and a boolean to check if the value has been set.
func (o *RestaurantContact) GetCityOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.City, true
}

// SetCity sets field value
func (o *RestaurantContact) SetCity(v string) {
	o.City = v
}

// GetPostalCode returns the PostalCode field value
func (o *RestaurantContact) GetPostalCode() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.PostalCode
}

// GetPostalCodeOk returns a tuple with the PostalCode field value
// and a boolean to check if the value has been set.
func (o *RestaurantContact) GetPostalCodeOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.PostalCode, true
}

// SetPostalCode sets field value
func (o *RestaurantContact) SetPostalCode(v string) {
	o.PostalCode = v
}

// GetCountryCode returns the CountryCode field value
func (o *RestaurantContact) GetCountryCode() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.CountryCode
}

// GetCountryCodeOk returns a tuple with the CountryCode field value
// and a boolean to check if the value has been set.
func (o *RestaurantContact) GetCountryCodeOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.CountryCode, true
}

// SetCountryCode sets field value
func (o *RestaurantContact) SetCountryCode(v string) {
	o.CountryCode = v
}

func (o RestaurantContact) MarshalJSON() ([]byte, error) {
	toSerialize,err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o RestaurantContact) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	toSerialize["phone_prefix"] = o.PhonePrefix
	toSerialize["phone_number"] = o.PhoneNumber
	toSerialize["email"] = o.Email
	toSerialize["address"] = o.Address
	toSerialize["city"] = o.City
	toSerialize["postal_code"] = o.PostalCode
	toSerialize["country_code"] = o.CountryCode
	return toSerialize, nil
}

func (o *RestaurantContact) UnmarshalJSON(data []byte) (err error) {
	// This validates that all required properties are included in the JSON object
	// by unmarshalling the object into a generic map with string keys and checking
	// that every required field exists as a key in the generic map.
	requiredProperties := []string{
		"phone_prefix",
		"phone_number",
		"email",
		"address",
		"city",
		"postal_code",
		"country_code",
	}

	allProperties := make(map[string]interface{})

	err = json.Unmarshal(data, &allProperties)

	if err != nil {
		return err;
	}

	for _, requiredProperty := range(requiredProperties) {
		if _, exists := allProperties[requiredProperty]; !exists {
			return fmt.Errorf("no value given for required property %v", requiredProperty)
		}
	}

	varRestaurantContact := _RestaurantContact{}

	decoder := json.NewDecoder(bytes.NewReader(data))
	decoder.DisallowUnknownFields()
	err = decoder.Decode(&varRestaurantContact)

	if err != nil {
		return err
	}

	*o = RestaurantContact(varRestaurantContact)

	return err
}

type NullableRestaurantContact struct {
	value *RestaurantContact
	isSet bool
}

func (v NullableRestaurantContact) Get() *RestaurantContact {
	return v.value
}

func (v *NullableRestaurantContact) Set(val *RestaurantContact) {
	v.value = val
	v.isSet = true
}

func (v NullableRestaurantContact) IsSet() bool {
	return v.isSet
}

func (v *NullableRestaurantContact) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableRestaurantContact(val *RestaurantContact) *NullableRestaurantContact {
	return &NullableRestaurantContact{value: val, isSet: true}
}

func (v NullableRestaurantContact) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableRestaurantContact) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


