/*
Restaurant Service API

API documentation for the restaurant service.  This service provides endpoints for restaurant and staff registration and management. 

API version: 1.0.0
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package restaurantclient

import (
	"encoding/json"
	"bytes"
	"fmt"
)

// checks if the RegisterRestaurantRequestRestaurant type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &RegisterRestaurantRequestRestaurant{}

// RegisterRestaurantRequestRestaurant struct for RegisterRestaurantRequestRestaurant
type RegisterRestaurantRequestRestaurant struct {
	// Restaurant's VAT code
	VatCode string `json:"vat_code"`
	// Restaurant's commercial name
	Name string `json:"name"`
	// Restaurant's legal name
	LegalName string `json:"legal_name"`
	// Restaurant's tax identification number
	TaxId *string `json:"tax_id,omitempty"`
	// IANA Restaurant's timezone identifier
	TimezoneId string `json:"timezone_id" validate:"regexp=^[A-Za-z_]+\\/[A-Za-z_]+$"`
	Contact RestaurantContact `json:"contact"`
}

type _RegisterRestaurantRequestRestaurant RegisterRestaurantRequestRestaurant

// NewRegisterRestaurantRequestRestaurant instantiates a new RegisterRestaurantRequestRestaurant object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewRegisterRestaurantRequestRestaurant(vatCode string, name string, legalName string, timezoneId string, contact RestaurantContact) *RegisterRestaurantRequestRestaurant {
	this := RegisterRestaurantRequestRestaurant{}
	this.VatCode = vatCode
	this.Name = name
	this.LegalName = legalName
	var taxId string = ""
	this.TaxId = &taxId
	this.TimezoneId = timezoneId
	this.Contact = contact
	return &this
}

// NewRegisterRestaurantRequestRestaurantWithDefaults instantiates a new RegisterRestaurantRequestRestaurant object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewRegisterRestaurantRequestRestaurantWithDefaults() *RegisterRestaurantRequestRestaurant {
	this := RegisterRestaurantRequestRestaurant{}
	var taxId string = ""
	this.TaxId = &taxId
	return &this
}

// GetVatCode returns the VatCode field value
func (o *RegisterRestaurantRequestRestaurant) GetVatCode() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.VatCode
}

// GetVatCodeOk returns a tuple with the VatCode field value
// and a boolean to check if the value has been set.
func (o *RegisterRestaurantRequestRestaurant) GetVatCodeOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.VatCode, true
}

// SetVatCode sets field value
func (o *RegisterRestaurantRequestRestaurant) SetVatCode(v string) {
	o.VatCode = v
}

// GetName returns the Name field value
func (o *RegisterRestaurantRequestRestaurant) GetName() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.Name
}

// GetNameOk returns a tuple with the Name field value
// and a boolean to check if the value has been set.
func (o *RegisterRestaurantRequestRestaurant) GetNameOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Name, true
}

// SetName sets field value
func (o *RegisterRestaurantRequestRestaurant) SetName(v string) {
	o.Name = v
}

// GetLegalName returns the LegalName field value
func (o *RegisterRestaurantRequestRestaurant) GetLegalName() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.LegalName
}

// GetLegalNameOk returns a tuple with the LegalName field value
// and a boolean to check if the value has been set.
func (o *RegisterRestaurantRequestRestaurant) GetLegalNameOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.LegalName, true
}

// SetLegalName sets field value
func (o *RegisterRestaurantRequestRestaurant) SetLegalName(v string) {
	o.LegalName = v
}

// GetTaxId returns the TaxId field value if set, zero value otherwise.
func (o *RegisterRestaurantRequestRestaurant) GetTaxId() string {
	if o == nil || IsNil(o.TaxId) {
		var ret string
		return ret
	}
	return *o.TaxId
}

// GetTaxIdOk returns a tuple with the TaxId field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *RegisterRestaurantRequestRestaurant) GetTaxIdOk() (*string, bool) {
	if o == nil || IsNil(o.TaxId) {
		return nil, false
	}
	return o.TaxId, true
}

// HasTaxId returns a boolean if a field has been set.
func (o *RegisterRestaurantRequestRestaurant) HasTaxId() bool {
	if o != nil && !IsNil(o.TaxId) {
		return true
	}

	return false
}

// SetTaxId gets a reference to the given string and assigns it to the TaxId field.
func (o *RegisterRestaurantRequestRestaurant) SetTaxId(v string) {
	o.TaxId = &v
}

// GetTimezoneId returns the TimezoneId field value
func (o *RegisterRestaurantRequestRestaurant) GetTimezoneId() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.TimezoneId
}

// GetTimezoneIdOk returns a tuple with the TimezoneId field value
// and a boolean to check if the value has been set.
func (o *RegisterRestaurantRequestRestaurant) GetTimezoneIdOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.TimezoneId, true
}

// SetTimezoneId sets field value
func (o *RegisterRestaurantRequestRestaurant) SetTimezoneId(v string) {
	o.TimezoneId = v
}

// GetContact returns the Contact field value
func (o *RegisterRestaurantRequestRestaurant) GetContact() RestaurantContact {
	if o == nil {
		var ret RestaurantContact
		return ret
	}

	return o.Contact
}

// GetContactOk returns a tuple with the Contact field value
// and a boolean to check if the value has been set.
func (o *RegisterRestaurantRequestRestaurant) GetContactOk() (*RestaurantContact, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Contact, true
}

// SetContact sets field value
func (o *RegisterRestaurantRequestRestaurant) SetContact(v RestaurantContact) {
	o.Contact = v
}

func (o RegisterRestaurantRequestRestaurant) MarshalJSON() ([]byte, error) {
	toSerialize,err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o RegisterRestaurantRequestRestaurant) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	toSerialize["vat_code"] = o.VatCode
	toSerialize["name"] = o.Name
	toSerialize["legal_name"] = o.LegalName
	if !IsNil(o.TaxId) {
		toSerialize["tax_id"] = o.TaxId
	}
	toSerialize["timezone_id"] = o.TimezoneId
	toSerialize["contact"] = o.Contact
	return toSerialize, nil
}

func (o *RegisterRestaurantRequestRestaurant) UnmarshalJSON(data []byte) (err error) {
	// This validates that all required properties are included in the JSON object
	// by unmarshalling the object into a generic map with string keys and checking
	// that every required field exists as a key in the generic map.
	requiredProperties := []string{
		"vat_code",
		"name",
		"legal_name",
		"timezone_id",
		"contact",
	}

	allProperties := make(map[string]interface{})

	err = json.Unmarshal(data, &allProperties)

	if err != nil {
		return err;
	}

	for _, requiredProperty := range(requiredProperties) {
		if _, exists := allProperties[requiredProperty]; !exists {
			return fmt.Errorf("no value given for required property %v", requiredProperty)
		}
	}

	varRegisterRestaurantRequestRestaurant := _RegisterRestaurantRequestRestaurant{}

	decoder := json.NewDecoder(bytes.NewReader(data))
	decoder.DisallowUnknownFields()
	err = decoder.Decode(&varRegisterRestaurantRequestRestaurant)

	if err != nil {
		return err
	}

	*o = RegisterRestaurantRequestRestaurant(varRegisterRestaurantRequestRestaurant)

	return err
}

type NullableRegisterRestaurantRequestRestaurant struct {
	value *RegisterRestaurantRequestRestaurant
	isSet bool
}

func (v NullableRegisterRestaurantRequestRestaurant) Get() *RegisterRestaurantRequestRestaurant {
	return v.value
}

func (v *NullableRegisterRestaurantRequestRestaurant) Set(val *RegisterRestaurantRequestRestaurant) {
	v.value = val
	v.isSet = true
}

func (v NullableRegisterRestaurantRequestRestaurant) IsSet() bool {
	return v.isSet
}

func (v *NullableRegisterRestaurantRequestRestaurant) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableRegisterRestaurantRequestRestaurant(val *RegisterRestaurantRequestRestaurant) *NullableRegisterRestaurantRequestRestaurant {
	return &NullableRegisterRestaurantRequestRestaurant{value: val, isSet: true}
}

func (v NullableRegisterRestaurantRequestRestaurant) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableRegisterRestaurantRequestRestaurant) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


