/*
Restaurant Service API

API documentation for the restaurant service.  This service provides endpoints for restaurant and staff registration and management. 

API version: 1.0.0
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package restaurantclient

import (
	"encoding/json"
	"bytes"
	"fmt"
)

// checks if the RegisterRestaurantRequestStaffOwner type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &RegisterRestaurantRequestStaffOwner{}

// RegisterRestaurantRequestStaffOwner struct for RegisterRestaurantRequestStaffOwner
type RegisterRestaurantRequestStaffOwner struct {
	// Staff owner's email address
	Email string `json:"email" validate:"regexp=^[\\\\w\\\\.-]+@[\\\\w\\\\.-]+\\\\.\\\\w{2,}$"`
	// Password must be at least 8 characters long
	Password string `json:"password"`
	// Staff owner's full name
	Name string `json:"name"`
	// Staff owner's address
	Address string `json:"address"`
	// Staff owner's city
	City string `json:"city"`
	// Staff owner's postal code
	PostalCode string `json:"postal_code"`
	// Staff owner's country code in ISO 3166-1 alpha-2 format
	CountryCode string `json:"country_code"`
}

type _RegisterRestaurantRequestStaffOwner RegisterRestaurantRequestStaffOwner

// NewRegisterRestaurantRequestStaffOwner instantiates a new RegisterRestaurantRequestStaffOwner object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewRegisterRestaurantRequestStaffOwner(email string, password string, name string, address string, city string, postalCode string, countryCode string) *RegisterRestaurantRequestStaffOwner {
	this := RegisterRestaurantRequestStaffOwner{}
	this.Email = email
	this.Password = password
	this.Name = name
	this.Address = address
	this.City = city
	this.PostalCode = postalCode
	this.CountryCode = countryCode
	return &this
}

// NewRegisterRestaurantRequestStaffOwnerWithDefaults instantiates a new RegisterRestaurantRequestStaffOwner object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewRegisterRestaurantRequestStaffOwnerWithDefaults() *RegisterRestaurantRequestStaffOwner {
	this := RegisterRestaurantRequestStaffOwner{}
	return &this
}

// GetEmail returns the Email field value
func (o *RegisterRestaurantRequestStaffOwner) GetEmail() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.Email
}

// GetEmailOk returns a tuple with the Email field value
// and a boolean to check if the value has been set.
func (o *RegisterRestaurantRequestStaffOwner) GetEmailOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Email, true
}

// SetEmail sets field value
func (o *RegisterRestaurantRequestStaffOwner) SetEmail(v string) {
	o.Email = v
}

// GetPassword returns the Password field value
func (o *RegisterRestaurantRequestStaffOwner) GetPassword() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.Password
}

// GetPasswordOk returns a tuple with the Password field value
// and a boolean to check if the value has been set.
func (o *RegisterRestaurantRequestStaffOwner) GetPasswordOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Password, true
}

// SetPassword sets field value
func (o *RegisterRestaurantRequestStaffOwner) SetPassword(v string) {
	o.Password = v
}

// GetName returns the Name field value
func (o *RegisterRestaurantRequestStaffOwner) GetName() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.Name
}

// GetNameOk returns a tuple with the Name field value
// and a boolean to check if the value has been set.
func (o *RegisterRestaurantRequestStaffOwner) GetNameOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Name, true
}

// SetName sets field value
func (o *RegisterRestaurantRequestStaffOwner) SetName(v string) {
	o.Name = v
}

// GetAddress returns the Address field value
func (o *RegisterRestaurantRequestStaffOwner) GetAddress() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.Address
}

// GetAddressOk returns a tuple with the Address field value
// and a boolean to check if the value has been set.
func (o *RegisterRestaurantRequestStaffOwner) GetAddressOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Address, true
}

// SetAddress sets field value
func (o *RegisterRestaurantRequestStaffOwner) SetAddress(v string) {
	o.Address = v
}

// GetCity returns the City field value
func (o *RegisterRestaurantRequestStaffOwner) GetCity() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.City
}

// GetCityOk returns a tuple with the City field value
// and a boolean to check if the value has been set.
func (o *RegisterRestaurantRequestStaffOwner) GetCityOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.City, true
}

// SetCity sets field value
func (o *RegisterRestaurantRequestStaffOwner) SetCity(v string) {
	o.City = v
}

// GetPostalCode returns the PostalCode field value
func (o *RegisterRestaurantRequestStaffOwner) GetPostalCode() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.PostalCode
}

// GetPostalCodeOk returns a tuple with the PostalCode field value
// and a boolean to check if the value has been set.
func (o *RegisterRestaurantRequestStaffOwner) GetPostalCodeOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.PostalCode, true
}

// SetPostalCode sets field value
func (o *RegisterRestaurantRequestStaffOwner) SetPostalCode(v string) {
	o.PostalCode = v
}

// GetCountryCode returns the CountryCode field value
func (o *RegisterRestaurantRequestStaffOwner) GetCountryCode() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.CountryCode
}

// GetCountryCodeOk returns a tuple with the CountryCode field value
// and a boolean to check if the value has been set.
func (o *RegisterRestaurantRequestStaffOwner) GetCountryCodeOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.CountryCode, true
}

// SetCountryCode sets field value
func (o *RegisterRestaurantRequestStaffOwner) SetCountryCode(v string) {
	o.CountryCode = v
}

func (o RegisterRestaurantRequestStaffOwner) MarshalJSON() ([]byte, error) {
	toSerialize,err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o RegisterRestaurantRequestStaffOwner) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	toSerialize["email"] = o.Email
	toSerialize["password"] = o.Password
	toSerialize["name"] = o.Name
	toSerialize["address"] = o.Address
	toSerialize["city"] = o.City
	toSerialize["postal_code"] = o.PostalCode
	toSerialize["country_code"] = o.CountryCode
	return toSerialize, nil
}

func (o *RegisterRestaurantRequestStaffOwner) UnmarshalJSON(data []byte) (err error) {
	// This validates that all required properties are included in the JSON object
	// by unmarshalling the object into a generic map with string keys and checking
	// that every required field exists as a key in the generic map.
	requiredProperties := []string{
		"email",
		"password",
		"name",
		"address",
		"city",
		"postal_code",
		"country_code",
	}

	allProperties := make(map[string]interface{})

	err = json.Unmarshal(data, &allProperties)

	if err != nil {
		return err;
	}

	for _, requiredProperty := range(requiredProperties) {
		if _, exists := allProperties[requiredProperty]; !exists {
			return fmt.Errorf("no value given for required property %v", requiredProperty)
		}
	}

	varRegisterRestaurantRequestStaffOwner := _RegisterRestaurantRequestStaffOwner{}

	decoder := json.NewDecoder(bytes.NewReader(data))
	decoder.DisallowUnknownFields()
	err = decoder.Decode(&varRegisterRestaurantRequestStaffOwner)

	if err != nil {
		return err
	}

	*o = RegisterRestaurantRequestStaffOwner(varRegisterRestaurantRequestStaffOwner)

	return err
}

type NullableRegisterRestaurantRequestStaffOwner struct {
	value *RegisterRestaurantRequestStaffOwner
	isSet bool
}

func (v NullableRegisterRestaurantRequestStaffOwner) Get() *RegisterRestaurantRequestStaffOwner {
	return v.value
}

func (v *NullableRegisterRestaurantRequestStaffOwner) Set(val *RegisterRestaurantRequestStaffOwner) {
	v.value = val
	v.isSet = true
}

func (v NullableRegisterRestaurantRequestStaffOwner) IsSet() bool {
	return v.isSet
}

func (v *NullableRegisterRestaurantRequestStaffOwner) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableRegisterRestaurantRequestStaffOwner(val *RegisterRestaurantRequestStaffOwner) *NullableRegisterRestaurantRequestStaffOwner {
	return &NullableRegisterRestaurantRequestStaffOwner{value: val, isSet: true}
}

func (v NullableRegisterRestaurantRequestStaffOwner) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableRegisterRestaurantRequestStaffOwner) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


