/*
Restaurant Service API

API documentation for the restaurant service.  This service provides endpoints for restaurant and staff registration and management. 

API version: 1.0.0
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package restaurantclient

import (
	"encoding/json"
	"time"
	"bytes"
	"fmt"
)

// checks if the Restaurant type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &Restaurant{}

// Restaurant struct for Restaurant
type Restaurant struct {
	// Unique restaurant identifier
	Id *string `json:"id,omitempty" validate:"regexp=^[0-9a-fA-F]{24}$"`
	// Restaurant's VAT code
	VatCode string `json:"vat_code"`
	// Restaurant's commercial name
	Name string `json:"name"`
	// Restaurant's legal name
	LegalName string `json:"legal_name"`
	// Restaurant's tax identification number
	TaxId *string `json:"tax_id,omitempty"`
	// IANA Restaurant's timezone identifier
	TimezoneId string `json:"timezone_id" validate:"regexp=^[A-Za-z_]+\\/[A-Za-z_]+$"`
	Contact RestaurantContact `json:"contact"`
	// Restaurant creation timestamp
	CreatedAt *time.Time `json:"created_at,omitempty"`
	// Restaurant last update timestamp
	UpdatedAt *time.Time `json:"updated_at,omitempty"`
}

type _Restaurant Restaurant

// NewRestaurant instantiates a new Restaurant object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewRestaurant(vatCode string, name string, legalName string, timezoneId string, contact RestaurantContact) *Restaurant {
	this := Restaurant{}
	this.VatCode = vatCode
	this.Name = name
	this.LegalName = legalName
	this.TimezoneId = timezoneId
	this.Contact = contact
	return &this
}

// NewRestaurantWithDefaults instantiates a new Restaurant object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewRestaurantWithDefaults() *Restaurant {
	this := Restaurant{}
	return &this
}

// GetId returns the Id field value if set, zero value otherwise.
func (o *Restaurant) GetId() string {
	if o == nil || IsNil(o.Id) {
		var ret string
		return ret
	}
	return *o.Id
}

// GetIdOk returns a tuple with the Id field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *Restaurant) GetIdOk() (*string, bool) {
	if o == nil || IsNil(o.Id) {
		return nil, false
	}
	return o.Id, true
}

// HasId returns a boolean if a field has been set.
func (o *Restaurant) HasId() bool {
	if o != nil && !IsNil(o.Id) {
		return true
	}

	return false
}

// SetId gets a reference to the given string and assigns it to the Id field.
func (o *Restaurant) SetId(v string) {
	o.Id = &v
}

// GetVatCode returns the VatCode field value
func (o *Restaurant) GetVatCode() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.VatCode
}

// GetVatCodeOk returns a tuple with the VatCode field value
// and a boolean to check if the value has been set.
func (o *Restaurant) GetVatCodeOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.VatCode, true
}

// SetVatCode sets field value
func (o *Restaurant) SetVatCode(v string) {
	o.VatCode = v
}

// GetName returns the Name field value
func (o *Restaurant) GetName() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.Name
}

// GetNameOk returns a tuple with the Name field value
// and a boolean to check if the value has been set.
func (o *Restaurant) GetNameOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Name, true
}

// SetName sets field value
func (o *Restaurant) SetName(v string) {
	o.Name = v
}

// GetLegalName returns the LegalName field value
func (o *Restaurant) GetLegalName() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.LegalName
}

// GetLegalNameOk returns a tuple with the LegalName field value
// and a boolean to check if the value has been set.
func (o *Restaurant) GetLegalNameOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.LegalName, true
}

// SetLegalName sets field value
func (o *Restaurant) SetLegalName(v string) {
	o.LegalName = v
}

// GetTaxId returns the TaxId field value if set, zero value otherwise.
func (o *Restaurant) GetTaxId() string {
	if o == nil || IsNil(o.TaxId) {
		var ret string
		return ret
	}
	return *o.TaxId
}

// GetTaxIdOk returns a tuple with the TaxId field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *Restaurant) GetTaxIdOk() (*string, bool) {
	if o == nil || IsNil(o.TaxId) {
		return nil, false
	}
	return o.TaxId, true
}

// HasTaxId returns a boolean if a field has been set.
func (o *Restaurant) HasTaxId() bool {
	if o != nil && !IsNil(o.TaxId) {
		return true
	}

	return false
}

// SetTaxId gets a reference to the given string and assigns it to the TaxId field.
func (o *Restaurant) SetTaxId(v string) {
	o.TaxId = &v
}

// GetTimezoneId returns the TimezoneId field value
func (o *Restaurant) GetTimezoneId() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.TimezoneId
}

// GetTimezoneIdOk returns a tuple with the TimezoneId field value
// and a boolean to check if the value has been set.
func (o *Restaurant) GetTimezoneIdOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.TimezoneId, true
}

// SetTimezoneId sets field value
func (o *Restaurant) SetTimezoneId(v string) {
	o.TimezoneId = v
}

// GetContact returns the Contact field value
func (o *Restaurant) GetContact() RestaurantContact {
	if o == nil {
		var ret RestaurantContact
		return ret
	}

	return o.Contact
}

// GetContactOk returns a tuple with the Contact field value
// and a boolean to check if the value has been set.
func (o *Restaurant) GetContactOk() (*RestaurantContact, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Contact, true
}

// SetContact sets field value
func (o *Restaurant) SetContact(v RestaurantContact) {
	o.Contact = v
}

// GetCreatedAt returns the CreatedAt field value if set, zero value otherwise.
func (o *Restaurant) GetCreatedAt() time.Time {
	if o == nil || IsNil(o.CreatedAt) {
		var ret time.Time
		return ret
	}
	return *o.CreatedAt
}

// GetCreatedAtOk returns a tuple with the CreatedAt field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *Restaurant) GetCreatedAtOk() (*time.Time, bool) {
	if o == nil || IsNil(o.CreatedAt) {
		return nil, false
	}
	return o.CreatedAt, true
}

// HasCreatedAt returns a boolean if a field has been set.
func (o *Restaurant) HasCreatedAt() bool {
	if o != nil && !IsNil(o.CreatedAt) {
		return true
	}

	return false
}

// SetCreatedAt gets a reference to the given time.Time and assigns it to the CreatedAt field.
func (o *Restaurant) SetCreatedAt(v time.Time) {
	o.CreatedAt = &v
}

// GetUpdatedAt returns the UpdatedAt field value if set, zero value otherwise.
func (o *Restaurant) GetUpdatedAt() time.Time {
	if o == nil || IsNil(o.UpdatedAt) {
		var ret time.Time
		return ret
	}
	return *o.UpdatedAt
}

// GetUpdatedAtOk returns a tuple with the UpdatedAt field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *Restaurant) GetUpdatedAtOk() (*time.Time, bool) {
	if o == nil || IsNil(o.UpdatedAt) {
		return nil, false
	}
	return o.UpdatedAt, true
}

// HasUpdatedAt returns a boolean if a field has been set.
func (o *Restaurant) HasUpdatedAt() bool {
	if o != nil && !IsNil(o.UpdatedAt) {
		return true
	}

	return false
}

// SetUpdatedAt gets a reference to the given time.Time and assigns it to the UpdatedAt field.
func (o *Restaurant) SetUpdatedAt(v time.Time) {
	o.UpdatedAt = &v
}

func (o Restaurant) MarshalJSON() ([]byte, error) {
	toSerialize,err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o Restaurant) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	if !IsNil(o.Id) {
		toSerialize["id"] = o.Id
	}
	toSerialize["vat_code"] = o.VatCode
	toSerialize["name"] = o.Name
	toSerialize["legal_name"] = o.LegalName
	if !IsNil(o.TaxId) {
		toSerialize["tax_id"] = o.TaxId
	}
	toSerialize["timezone_id"] = o.TimezoneId
	toSerialize["contact"] = o.Contact
	if !IsNil(o.CreatedAt) {
		toSerialize["created_at"] = o.CreatedAt
	}
	if !IsNil(o.UpdatedAt) {
		toSerialize["updated_at"] = o.UpdatedAt
	}
	return toSerialize, nil
}

func (o *Restaurant) UnmarshalJSON(data []byte) (err error) {
	// This validates that all required properties are included in the JSON object
	// by unmarshalling the object into a generic map with string keys and checking
	// that every required field exists as a key in the generic map.
	requiredProperties := []string{
		"vat_code",
		"name",
		"legal_name",
		"timezone_id",
		"contact",
	}

	allProperties := make(map[string]interface{})

	err = json.Unmarshal(data, &allProperties)

	if err != nil {
		return err;
	}

	for _, requiredProperty := range(requiredProperties) {
		if _, exists := allProperties[requiredProperty]; !exists {
			return fmt.Errorf("no value given for required property %v", requiredProperty)
		}
	}

	varRestaurant := _Restaurant{}

	decoder := json.NewDecoder(bytes.NewReader(data))
	decoder.DisallowUnknownFields()
	err = decoder.Decode(&varRestaurant)

	if err != nil {
		return err
	}

	*o = Restaurant(varRestaurant)

	return err
}

type NullableRestaurant struct {
	value *Restaurant
	isSet bool
}

func (v NullableRestaurant) Get() *Restaurant {
	return v.value
}

func (v *NullableRestaurant) Set(val *Restaurant) {
	v.value = val
	v.isSet = true
}

func (v NullableRestaurant) IsSet() bool {
	return v.isSet
}

func (v *NullableRestaurant) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableRestaurant(val *Restaurant) *NullableRestaurant {
	return &NullableRestaurant{value: val, isSet: true}
}

func (v NullableRestaurant) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableRestaurant) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


