/*
Restaurant Service API

API documentation for the restaurant service.  This service provides endpoints for restaurant and staff registration and management. 

API version: 1.0.0
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package restaurantclient

import (
	"encoding/json"
	"bytes"
	"fmt"
)

// checks if the RegisterRestaurantResponse type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &RegisterRestaurantResponse{}

// RegisterRestaurantResponse struct for RegisterRestaurantResponse
type RegisterRestaurantResponse struct {
	Restaurant Restaurant `json:"restaurant"`
	StaffOwner Staff `json:"staff_owner"`
}

type _RegisterRestaurantResponse RegisterRestaurantResponse

// NewRegisterRestaurantResponse instantiates a new RegisterRestaurantResponse object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewRegisterRestaurantResponse(restaurant Restaurant, staffOwner Staff) *RegisterRestaurantResponse {
	this := RegisterRestaurantResponse{}
	this.Restaurant = restaurant
	this.StaffOwner = staffOwner
	return &this
}

// NewRegisterRestaurantResponseWithDefaults instantiates a new RegisterRestaurantResponse object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewRegisterRestaurantResponseWithDefaults() *RegisterRestaurantResponse {
	this := RegisterRestaurantResponse{}
	return &this
}

// GetRestaurant returns the Restaurant field value
func (o *RegisterRestaurantResponse) GetRestaurant() Restaurant {
	if o == nil {
		var ret Restaurant
		return ret
	}

	return o.Restaurant
}

// GetRestaurantOk returns a tuple with the Restaurant field value
// and a boolean to check if the value has been set.
func (o *RegisterRestaurantResponse) GetRestaurantOk() (*Restaurant, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Restaurant, true
}

// SetRestaurant sets field value
func (o *RegisterRestaurantResponse) SetRestaurant(v Restaurant) {
	o.Restaurant = v
}

// GetStaffOwner returns the StaffOwner field value
func (o *RegisterRestaurantResponse) GetStaffOwner() Staff {
	if o == nil {
		var ret Staff
		return ret
	}

	return o.StaffOwner
}

// GetStaffOwnerOk returns a tuple with the StaffOwner field value
// and a boolean to check if the value has been set.
func (o *RegisterRestaurantResponse) GetStaffOwnerOk() (*Staff, bool) {
	if o == nil {
		return nil, false
	}
	return &o.StaffOwner, true
}

// SetStaffOwner sets field value
func (o *RegisterRestaurantResponse) SetStaffOwner(v Staff) {
	o.StaffOwner = v
}

func (o RegisterRestaurantResponse) MarshalJSON() ([]byte, error) {
	toSerialize,err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o RegisterRestaurantResponse) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	toSerialize["restaurant"] = o.Restaurant
	toSerialize["staff_owner"] = o.StaffOwner
	return toSerialize, nil
}

func (o *RegisterRestaurantResponse) UnmarshalJSON(data []byte) (err error) {
	// This validates that all required properties are included in the JSON object
	// by unmarshalling the object into a generic map with string keys and checking
	// that every required field exists as a key in the generic map.
	requiredProperties := []string{
		"restaurant",
		"staff_owner",
	}

	allProperties := make(map[string]interface{})

	err = json.Unmarshal(data, &allProperties)

	if err != nil {
		return err;
	}

	for _, requiredProperty := range(requiredProperties) {
		if _, exists := allProperties[requiredProperty]; !exists {
			return fmt.Errorf("no value given for required property %v", requiredProperty)
		}
	}

	varRegisterRestaurantResponse := _RegisterRestaurantResponse{}

	decoder := json.NewDecoder(bytes.NewReader(data))
	decoder.DisallowUnknownFields()
	err = decoder.Decode(&varRegisterRestaurantResponse)

	if err != nil {
		return err
	}

	*o = RegisterRestaurantResponse(varRegisterRestaurantResponse)

	return err
}

type NullableRegisterRestaurantResponse struct {
	value *RegisterRestaurantResponse
	isSet bool
}

func (v NullableRegisterRestaurantResponse) Get() *RegisterRestaurantResponse {
	return v.value
}

func (v *NullableRegisterRestaurantResponse) Set(val *RegisterRestaurantResponse) {
	v.value = val
	v.isSet = true
}

func (v NullableRegisterRestaurantResponse) IsSet() bool {
	return v.isSet
}

func (v *NullableRegisterRestaurantResponse) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableRegisterRestaurantResponse(val *RegisterRestaurantResponse) *NullableRegisterRestaurantResponse {
	return &NullableRegisterRestaurantResponse{value: val, isSet: true}
}

func (v NullableRegisterRestaurantResponse) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableRegisterRestaurantResponse) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


