/*
Restaurant Service API

API documentation for the restaurant service.  This service provides endpoints for restaurant and staff registration and management. 

API version: 1.0.0
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package restaurantclient

import (
	"encoding/json"
	"bytes"
	"fmt"
)

// checks if the RegisterRestaurantRequest type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &RegisterRestaurantRequest{}

// RegisterRestaurantRequest struct for RegisterRestaurantRequest
type RegisterRestaurantRequest struct {
	Restaurant RegisterRestaurantRequestRestaurant `json:"restaurant"`
	StaffOwner RegisterRestaurantRequestStaffOwner `json:"staff_owner"`
}

type _RegisterRestaurantRequest RegisterRestaurantRequest

// NewRegisterRestaurantRequest instantiates a new RegisterRestaurantRequest object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewRegisterRestaurantRequest(restaurant RegisterRestaurantRequestRestaurant, staffOwner RegisterRestaurantRequestStaffOwner) *RegisterRestaurantRequest {
	this := RegisterRestaurantRequest{}
	this.Restaurant = restaurant
	this.StaffOwner = staffOwner
	return &this
}

// NewRegisterRestaurantRequestWithDefaults instantiates a new RegisterRestaurantRequest object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewRegisterRestaurantRequestWithDefaults() *RegisterRestaurantRequest {
	this := RegisterRestaurantRequest{}
	return &this
}

// GetRestaurant returns the Restaurant field value
func (o *RegisterRestaurantRequest) GetRestaurant() RegisterRestaurantRequestRestaurant {
	if o == nil {
		var ret RegisterRestaurantRequestRestaurant
		return ret
	}

	return o.Restaurant
}

// GetRestaurantOk returns a tuple with the Restaurant field value
// and a boolean to check if the value has been set.
func (o *RegisterRestaurantRequest) GetRestaurantOk() (*RegisterRestaurantRequestRestaurant, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Restaurant, true
}

// SetRestaurant sets field value
func (o *RegisterRestaurantRequest) SetRestaurant(v RegisterRestaurantRequestRestaurant) {
	o.Restaurant = v
}

// GetStaffOwner returns the StaffOwner field value
func (o *RegisterRestaurantRequest) GetStaffOwner() RegisterRestaurantRequestStaffOwner {
	if o == nil {
		var ret RegisterRestaurantRequestStaffOwner
		return ret
	}

	return o.StaffOwner
}

// GetStaffOwnerOk returns a tuple with the StaffOwner field value
// and a boolean to check if the value has been set.
func (o *RegisterRestaurantRequest) GetStaffOwnerOk() (*RegisterRestaurantRequestStaffOwner, bool) {
	if o == nil {
		return nil, false
	}
	return &o.StaffOwner, true
}

// SetStaffOwner sets field value
func (o *RegisterRestaurantRequest) SetStaffOwner(v RegisterRestaurantRequestStaffOwner) {
	o.StaffOwner = v
}

func (o RegisterRestaurantRequest) MarshalJSON() ([]byte, error) {
	toSerialize,err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o RegisterRestaurantRequest) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	toSerialize["restaurant"] = o.Restaurant
	toSerialize["staff_owner"] = o.StaffOwner
	return toSerialize, nil
}

func (o *RegisterRestaurantRequest) UnmarshalJSON(data []byte) (err error) {
	// This validates that all required properties are included in the JSON object
	// by unmarshalling the object into a generic map with string keys and checking
	// that every required field exists as a key in the generic map.
	requiredProperties := []string{
		"restaurant",
		"staff_owner",
	}

	allProperties := make(map[string]interface{})

	err = json.Unmarshal(data, &allProperties)

	if err != nil {
		return err;
	}

	for _, requiredProperty := range(requiredProperties) {
		if _, exists := allProperties[requiredProperty]; !exists {
			return fmt.Errorf("no value given for required property %v", requiredProperty)
		}
	}

	varRegisterRestaurantRequest := _RegisterRestaurantRequest{}

	decoder := json.NewDecoder(bytes.NewReader(data))
	decoder.DisallowUnknownFields()
	err = decoder.Decode(&varRegisterRestaurantRequest)

	if err != nil {
		return err
	}

	*o = RegisterRestaurantRequest(varRegisterRestaurantRequest)

	return err
}

type NullableRegisterRestaurantRequest struct {
	value *RegisterRestaurantRequest
	isSet bool
}

func (v NullableRegisterRestaurantRequest) Get() *RegisterRestaurantRequest {
	return v.value
}

func (v *NullableRegisterRestaurantRequest) Set(val *RegisterRestaurantRequest) {
	v.value = val
	v.isSet = true
}

func (v NullableRegisterRestaurantRequest) IsSet() bool {
	return v.isSet
}

func (v *NullableRegisterRestaurantRequest) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableRegisterRestaurantRequest(val *RegisterRestaurantRequest) *NullableRegisterRestaurantRequest {
	return &NullableRegisterRestaurantRequest{value: val, isSet: true}
}

func (v NullableRegisterRestaurantRequest) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableRegisterRestaurantRequest) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


