openapi: 3.0.3
info:
  $ref: './info/info.yaml'

servers:
  $ref: './servers/severs.yaml'

security:
  - BearerAuth: []

tags:
  $ref: './tags/tags.yaml'

paths:
  /v1.0/customers/login:
    $ref: './paths/customers/login.yaml'
  /v1.0/customers/refresh:
    $ref: './paths/customers/refresh.yaml'
  /v1.0/auth/customers:
    $ref: './paths/customers/customers.yaml'
  /v1.0/auth/staff:
    $ref: './paths/staff/staff-users.yaml'

components:
  securitySchemes:
    $ref: './components/security/index.yaml'
  examples:
    $ref: './components/examples/index.yaml'
  schemas:
    $ref: './components/schemas/index.yaml'
  responses:
    $ref: './components/responses/index.yaml'
