//go:build integration

package staff_test

import (
	"context"
	"testing"
	"time"

	"github.com/stretchr/testify/assert"
	"go.mongodb.org/mongo-driver/bson"
	"go.mongodb.org/mongo-driver/mongo"
	"go.mongodb.org/mongo-driver/mongo/options"

	"github.com/alexgrauroca/practice-food-delivery-platform/pkg/clock"
	"github.com/alexgrauroca/practice-food-delivery-platform/pkg/infraestructure/mongodb"
	"github.com/alexgrauroca/practice-food-delivery-platform/pkg/log"
	"github.com/alexgrauroca/practice-food-delivery-platform/services/authentication-service/internal/staff"
)

type staffRepositoryTestCase[P, W any] struct {
	name            string
	insertDocuments func(t *testing.T, coll *mongo.Collection)
	params          P
	want            W
	wantErr         error
}

func TestRepository_CreateStaff(t *testing.T) {
	now := time.Date(2025, 1, 1, 0, 0, 0, 0, time.UTC)
	logger, _ := log.NewTest()

	tests := []staffRepositoryTestCase[staff.CreateStaffParams, staff.Staff]{
		{
			name: "when exists an active staff with the same email, then it should return a staff already exists error",
			insertDocuments: func(t *testing.T, coll *mongo.Collection) {
				mongodb.InsertTestDocument(t, coll, staff.Staff{
					StaffID:   "fake-staff-id",
					Email:     "test@example.com",
					Password:  "fakehashedpassword",
					Active:    true,
					CreatedAt: now,
					UpdatedAt: now,
				})
			},
			params: staff.CreateStaffParams{
				StaffID:  "fake-staff-id",
				Email:    "test@example.com",
				Password: "ValidPassword123",
			},
			want:    staff.Staff{},
			wantErr: staff.ErrStaffAlreadyExists,
		},
		{
			name: "when the staff is created successfully, then it should return the created staff",
			params: staff.CreateStaffParams{
				StaffID:  "fake-staff-id",
				Email:    "test@example.com",
				Password: "ValidPassword123",
			},
			want: staff.Staff{
				StaffID:   "fake-staff-id",
				Email:     "test@example.com",
				Active:    true,
				Password:  "ValidPassword123",
				CreatedAt: now,
				UpdatedAt: now,
			},
			wantErr: nil,
		},
	}

	for _, tt := range tests {
		t.Run(tt.name, func(t *testing.T) {
			tdb := mongodb.NewTestDB(t, "staff_test_authentication_service")
			defer tdb.Close(t)

			coll := setupTestStaffCollection(t, tdb.DB)
			if tt.insertDocuments != nil {
				tt.insertDocuments(t, coll)
			}

			repo := staff.NewRepository(logger, tdb.DB, clock.FixedClock{FixedTime: now})
			got, err := repo.CreateStaff(context.Background(), tt.params)

			// Error assertion
			assert.ErrorIs(t, err, tt.wantErr)

			// Validating the got only if there is no error expected
			if tt.wantErr == nil {
				// As the ID is generated by MongoDB, we just check that it is not empty
				assert.NotEmpty(t, got.ID, "ID should not be empty")

				// Doing this as in that way, I can do a direct equal assertion between the want ant got
				tt.want.ID = got.ID
				assert.Equal(t, tt.want, got)
			}
		})
	}
}

func TestRepository_CreateStaff_UnexpectedFailure(t *testing.T) {
	now := time.Date(2025, 1, 1, 0, 0, 0, 0, time.UTC)
	logger, _ := log.NewTest()

	tdb := mongodb.NewTestDB(t, "staff_test_authentication_service")
	repo := staff.NewRepository(logger, tdb.DB, clock.FixedClock{FixedTime: now})

	// Simulating an unexpected failure by closing the opened connection
	tdb.Close(t)

	_, err := repo.CreateStaff(context.Background(), staff.CreateStaffParams{})
	assert.Error(t, err, "Expected an error due to unexpected failure")
	assert.NotErrorIs(t, err, staff.ErrStaffAlreadyExists)
}

func setupTestStaffCollection(t *testing.T, db *mongo.Database) *mongo.Collection {
	ctx, cancel := context.WithTimeout(context.Background(), 5*time.Second)
	defer cancel()

	coll := db.Collection(staff.CollectionName)

	// Create unique index on email
	indexModel := mongo.IndexModel{
		Keys: bson.D{{Key: staff.FieldEmail, Value: 1}},
		Options: options.Index().
			SetUnique(true).
			SetPartialFilterExpression(bson.D{{Key: staff.FieldActive, Value: true}}),
	}
	if _, err := coll.Indexes().CreateOne(ctx, indexModel); err != nil {
		t.Fatalf("Failed to create unique index: %v", err)
	}

	return coll
}
