openapi-validate-sync:
	@cd ../.. && ./scripts/openapi-validate-sync.sh services/customer-service

openapi-validate-docs:
	@cd ../.. && ./scripts/openapi-validate-docs.sh services/customer-service

openapi-generate:
	@cd ../.. && ./scripts/openapi-bundle.sh services/customer-service
