#!/bin/bash
set -e

# Create temporary directory for comparison
TEMP_DIR=$(mktemp -d)
cp -r clients/ "$TEMP_DIR/"

# Generate clients using existing make targets
for service in services/*/; do
    if [ -f "${service}Makefile" ] && grep -q "generate-clients:" "${service}Makefile"; then
        echo "Generating clients for ${service}..."
        SERVICE_NAME=$(basename "$service")

        # Create the client directory if it doesn't exist
        mkdir -p "clients/${SERVICE_NAME}"

        # Generate the client using the service's make target
        (cd "$service" && make generate-clients)
    fi
done

# Function to clean up generated files for comparison
cleanup_generated_files() {
    local dir="$1"
    # Remove go.mod and go.sum as they might have different timestamps
    find "$dir" -name "go.mod" -delete
    find "$dir" -name "go.sum" -delete

    # Remove git-related files if any
    find "$dir" -name ".git*" -delete

    # Remove common generated timestamps and version comments
    for file in $(find "$dir" -type f -name "*.go"); do
        # Remove generated timestamp comments
        sed -i '/DO NOT EDIT./d' "$file" 2>/dev/null || true
        sed -i '/Code generated .* DO NOT EDIT./d' "$file" 2>/dev/null || true
        sed -i '/Generated by .* DO NOT EDIT./d' "$file" 2>/dev/null || true
    done
}

# Clean up both directories
cleanup_generated_files "clients/"
cleanup_generated_files "$TEMP_DIR/clients/"

# Compare with original, ignoring whitespace
if ! diff -rw clients/ "$TEMP_DIR/clients/" > /dev/null; then
    echo "::error::Generated clients are out of date. Please run 'make generate-clients' in the relevant services and commit the changes"
    echo "Differences found:"
    diff -rw clients/ "$TEMP_DIR/clients/" || true
    exit 1
fi

echo "Clients are up to date!"