generatorName: go
outputDir: ../../clients/authentication-service
packageName: authclient
gitUserId: alexgrauroca
gitRepoId: practice-food-delivery-platform
additionalProperties:
  module: github.com/alexgrauroca/practice-food-delivery-platform/authclient
  isGoSubmodule: "true"
  enumClassPrefix: "true"
  packageName: authclient
  disallowAdditionalPropertiesIfNotPresent: "true"
